#!/bin/bash

printf "Content-type: text/plain\n\n"
printf "PATH_INFO [%s]\n" ${PATH_INFO}
printf "RB_GLOBAL [%s]\n" ${RB_GLOBAL}
printf "Arg 1 [%s]\n" ${1}
printf "QUERY_STRING [%s]\n" ${QUERY_STRING}
printf "REMOTE_USER [%s]\n" ${REMOTE_USER}
printf "HTTP_TOKEN_CLAIM_USER [%s]\n" ${HTTP_TOKEN_CLAIM_USER}
if [ -z ${RB_LOCAL+x} ]; then 
	printf "RB_LOCAL is unset\n" 
else
	printf "RB_LOCAL is set to [%s]\n" ${RB_LOCAL}
fi
printf "example error message\n" > /dev/stderr
exit 0
